# Generated by Django 4.2 on 2025-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='trxid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
